### ISSUE TITLE
Bad practice with PhysicalResourceId

### ISSUE THREAD

**Issue by andrew-templeton** [sonyxperiadev/amazon-custom-resources#1]
You should not use `context.logStreamName` in `PhysicalResourceId` response objects. The `PhysicalResourceId` should be akin to an ARN. If this value is changes during an `UPDATE` action, then the CloudFormation stack will send a `DELETE` signal to the Logical Resource in the template during the `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS` lifecycle. If you do not change it, then the `CLEANUP` will not happen. In the presented example, this is fine, because you're just reading information, but if you were actually making resources, this would result in a lot of unexpected behavior.

Either change the implementation to use a unique request ID, or make a note to explain what the `PhysicalResourceId` actually does for custom resources.

**Comment by andersjanmyr** [comment]
@andrew-templeton Sorry, I have not been notified of this Issue for some reason.
I have updated the article to fit the code. The resources does not use this anymore because 
of the issues that you write about. Also, because a new resource would be created on every update.
